### ISSUE TITLE
ModuleNotFoundError: No module named 'geolib.cone'

### ISSUE THREAD

**Issue by seann999** [stanford-iprl-lab/UniGrasp#1]
```
Traceback (most recent call last):
  File "gripper_files_allegro.py", line 24, in <module>
    from grasp_reachability_nfinger import GraspConfig
  File "/home/sean/projects/UniGrasp/simulation/grasp_reachability_nfinger.py", line 33, in <module>
    from geolib.cone import Cone
ModuleNotFoundError: No module named 'geolib.cone'
```

There seems to be no cone.py in geolib?

**Comment by linsats** [comment]
I update the grasp_reachability_nfinger.py. It does not require the cone.py now.
